"use client";
import { Montserrat } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Header from "./_components/Header.jsx";
import Footer from "./_components/Footer";
import { useState } from "react";
import { CartContext } from "./_context/CartContext";
import GlobalApi from "./_utlis/GlobalApi";

const inter = Montserrat({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "E-Commerce NextJs Strapi Backend",
//   description: "Generated by create next app",
// };
export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);

  return (
    <ClerkProvider>
      <CartContext.Provider value={{ cart, setCart }}>
        <html lang="en">
          <body>
            <Header />
            <main>{children}</main>
            <Footer />
          </body>
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
